- name: Add the Elasticsearch YUM repository (CentOS)
  yum_repository:
    name: elasticsearch
    description: Elasticsearch repository
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
  when: ansible_distribution == "CentOS"
  become: yes

- name: Install Elasticsearch
  package:
    name: elasticsearch
    state: latest
  become: yes

- name: Start Elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes
  become: yes
